name: Cypress Tests

on: push

jobs:
  install:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress install
        uses: cypress-io/github-action@v6
        with:
          # Disable running of tests within install job
          runTests: false
      - name: Save build folder screenshots
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          #path over here according to your project
          path: Test/screenshots
          if-no-files-found: ignore
      - name: Save build folder videos
        uses: actions/upload-artifact@v3
        with:
          name: videos
          path: Test/videos
          if-no-files-found: ignore

  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Precommit
        run: npm ci
      - run: npm run precommit
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          browser: chrome